highlighter: rouge
markdown: kramdown
timezone: America/New_York
title: Slim Framework
url: http://www.slimframework.com
slim_version: v3
slim_docs_versions: v3, v4
slim_website_repo: https://github.com/slimphp/Slim-Website/tree/gh-pages/
urlBasePath:
include: [.htaccess]
exclude: [node_modules]
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
plugins:
  - jekyll-sitemap
algolia:
  application_id: KS0N5YSBFY
  index_name:     slim-docs
  nodes_to_index: 'h1,h2,h3,p,ul.toc-links.li'
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      docs-v4:
        - title: Get Started
          items:
          - [/docs/v4, Home]
          - [/docs/v4/start/installation.md, Installation]
          - [/docs/v4/start/upgrade.md, Upgrade Guide]
          - [/docs/v4/start/web-servers.md, Web Servers]
          - [/docs/v4/deployment/deployment.md, Deployment]
        - title: Concepts
          items:
          - [/docs/v4/concepts/life-cycle.md, Application Life Cycle]
          - [/docs/v4/concepts/value-objects.md, PSR-7]
          - [/docs/v4/concepts/middleware.md, Middleware]
          - [/docs/v4/concepts/di.md, Dependency Container]
        - title: The Application
          items:
          - [/docs/v4/objects/application.md, Overview]
          - [/docs/v4/objects/application.md#notices-and-warnings-handling, Notices & Warnings Handling]
        - title: The Request
          items:
          - [/docs/v4/objects/request.md, Overview]
          - [/docs/v4/objects/request.md#the-request-method, Method]
          - [/docs/v4/objects/request.md#the-request-headers, Headers]
          - [/docs/v4/objects/request.md#the-request-body, Body]
          - [/docs/v4/objects/request.md#uploaded-files, Uploaded Files]
          - [/docs/v4/objects/request.md#request-helpers, Helpers]
          - [/docs/v4/objects/request.md#route-object, Route object]
          - [/docs/v4/objects/request.md#media-type-parsers, Media type parsers]
        - title: The Response
          items:
          - [/docs/v4/objects/response.md, Overview]
          - [/docs/v4/objects/response.md#the-response-status, Status]
          - [/docs/v4/objects/response.md#the-response-headers, Headers]
          - [/docs/v4/objects/response.md#the-response-body, Body]
          - [/docs/v4/objects/response.md#returning-json, JSON]
        - title: Routing
          items:
          - [/docs/v4/objects/routing.md, Overview]
          - [/docs/v4/objects/routing.md#how-to-create-routes, Create Routes]
          - [/docs/v4/objects/routing.md#route-callbacks, Callbacks]
          - [/docs/v4/objects/routing.md#route-strategies, Strategies]
          - [/docs/v4/objects/routing.md#route-placeholders, Placeholders]
          - [/docs/v4/objects/routing.md#route-names, Names]
          - [/docs/v4/objects/routing.md#route-groups, Groups]
          - [/docs/v4/objects/routing.md#route-middleware, Middleware]
          - [/docs/v4/objects/routing.md#router-caching, Caching]
          - [/docs/v4/objects/routing.md#container-resolution, Container Resolution]
        - title: Packaged Middleware
          items:
          - [/docs/v4/middleware/routing.md, Routing]
          - [/docs/v4/middleware/error-handling.md, Error Handling]
          - [/docs/v4/middleware/method-overriding.md, Method Overriding]
          - [/docs/v4/middleware/output-buffering.md, Output Buffering]
          - [/docs/v4/middleware/content-length.md, Content Length]
        - title: Cook book
          items:
          - [/docs/v4/cookbook/route-patterns.md, Trailing / in routes]
          - [/docs/v4/cookbook/retrieving-current-route.md, Retrieving Current Route]
          - [/docs/v4/cookbook/enable-cors.md, Enabling CORS]
          - [/docs/v4/cookbook/uploading-files.md, Uploading Files using POST forms]
        - title: Contributing
          items:
          - [/docs/v4/contributors/strategy.md, Branching Strategy]
          - [/docs/v4/contributors/guidelines.md, Guidelines]

  - scope:
      path: "docs/v4"
      type: "pages"
    values:
      layout: docs-v4

  -
    scope:
      path: ""
      type: "pages"
    values:
      docs-v3:
        - title: まず最初に
          items:
            - [/docs/v3, Home]
            - [/docs/v3/start/installation.md, Install]
            - [/docs/v3/start/upgrade.md, Upgrade Guide]
            - [/docs/v3/start/web-servers.md, Web Servers]
            - [/docs/v3/deployment/deployment.md, Deployment]
        - title: チュートリアル
          items:
            - [/docs/v3/tutorial/first-app.md, First Application]
        - title: コンセプト
          items:
            - [/docs/v3/concepts/life-cycle.md, Application Life Cycle]
            - [/docs/v3/concepts/value-objects.md, PSR-7]
            - [/docs/v3/concepts/middleware.md, Middleware]
            - [/docs/v3/concepts/di.md, Dependency Container]
        - title: アプリケーション
          items:
            - [/docs/v3/objects/application.md, Overview]
            - [/docs/v3/objects/application.md#application-configuration, Configuration]
            - [/docs/v3/objects/application.md#slim-default-settings, Default settings]
        - title: リクエスト
          items:
            - [/docs/v3/objects/request.md, Overview]
            - [/docs/v3/objects/request.md#the-request-method, Method]
            - [/docs/v3/objects/request.md#the-request-headers, Headers]
            - [/docs/v3/objects/request.md#the-request-body, Body]
            - [/docs/v3/objects/request.md#uploaded-files, Uploaded Files]
            - [/docs/v3/objects/request.md#request-helpers, Helpers]
            - [/docs/v3/objects/request.md#route-object, Route object]
            - [/docs/v3/objects/request.md#media-type-parsers, Media type parsers]
        - title: レスポンス
          items:
            - [/docs/v3/objects/response.md, Overview]
            - [/docs/v3/objects/response.md#the-response-status, Status]
            - [/docs/v3/objects/response.md#the-response-headers, Headers]
            - [/docs/v3/objects/response.md#the-response-body, Body]
            - [/docs/v3/objects/response.md#returning-json, JSON]
        - title: ルーティング
          items:
            - [/docs/v3/objects/router.md, Overview]
            - [/docs/v3/objects/router.md#how-to-create-routes, Create Routes]
            - [/docs/v3/objects/router.md#route-callbacks, Callbacks]
            - [/docs/v3/objects/router.md#route-strategies, Strategies]
            - [/docs/v3/objects/router.md#route-placeholders, Placeholders]
            - [/docs/v3/objects/router.md#route-names, Names]
            - [/docs/v3/objects/router.md#route-groups, Groups]
            - [/docs/v3/objects/router.md#route-middleware, Middleware]
            - [/docs/v3/objects/router.md#container-resolution, Container Resolution]
        - title: エラー処理
          items:
            - [/docs/v3/handlers/error.md, Error Handlers]
            - [/docs/v3/handlers/not-found.md, 404 Not Found]
            - [/docs/v3/handlers/not-allowed.md, 405 Not Allowed]
            - [/docs/v3/handlers/php-error.md, PHP Runtime Error]
        - title: クックブック
          items:
            - [/docs/v3/cookbook/route-patterns.md, Trailing / in routes]
            - [/docs/v3/cookbook/ip-address.md, Retrieving IP address]
            - [/docs/v3/cookbook/retrieving-current-route.md, Retrieving Current Route]
            - [/docs/v3/cookbook/database-eloquent.md, Using Eloquent with Slim]
            - [/docs/v3/cookbook/database-doctrine.md, Using Doctrine with Slim]
            - [/docs/v3/cookbook/database-atlas.md, Using Atlas with Slim]
            - [/docs/v3/cookbook/enable-cors.md, Enabling CORS]
            - [/docs/v3/cookbook/environment.md, Getting and Mocking the Environment]
            - [/docs/v3/cookbook/uploading-files.md, Uploading Files using POST forms]
            - [/docs/v3/cookbook/action-domain-responder.md, Action-Domain-Responder with Slim]
        - title: アドオン
          items:
            - [/docs/v3/features/templates.md, Templates]
            - [/docs/v3/features/caching.md, HTTP Caching]
            - [/docs/v3/features/csrf.md, CSRF Protection]
            - [/docs/v3/features/flash.md, Flash Messages]
            - ['https://github.com/slimphp/Slim/wiki/Middleware-for-Slim-Framework-v3.x', 3rd Party]
        - title: 開発への協力
          items:
            - [/docs/v3/contributors/strategy.md, ブランチング方針]
            - [/docs/v3/contributors/guidelines.md, ガイドライン]

  - scope:
      path: "docs/v3"
      type: "pages"
    values:
      layout: docs-v3
